/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projeto;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import ArtManager.Main;
import Cliente.Cliente;
import Cliente.Cliente_CRUD;

/**
 *
 * @author Projetos ES
 */
public class Editar_Projetos extends javax.swing.JFrame {
    Projeto projeto;
    /**
     * Creates new form Incluir_Fornecedores
     */
    public Editar_Projetos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelJustificativa = new javax.swing.JLabel();
        jTextFieldJustificativa = new javax.swing.JTextField();
        jLabelDemocratizacao = new javax.swing.JLabel();
        jLabelAcessibilidade = new javax.swing.JLabel();
        jLabelPublicoEstimado = new javax.swing.JLabel();
        jLabelOrcamento = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jTextFieldDemocratizacao = new javax.swing.JTextField();
        jTextFieldAcessibilidade = new javax.swing.JTextField();
        jTextFieldPublicoEstimado = new javax.swing.JTextField();
        jTextFieldOrcamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelDescricao = new javax.swing.JLabel();
        jLabelArtista = new javax.swing.JLabel();
        jTextFieldDescricao = new javax.swing.JTextField();
        jButtonCadastrarArtistas = new javax.swing.JButton();
        jLabelObjetivo = new javax.swing.JLabel();
        jLabelProdutos = new javax.swing.JLabel();
        jTextFieldObjetivo = new javax.swing.JTextField();
        jButtonCadastrarProdutos = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jTextFieldLocal = new javax.swing.JTextField();
        jLabelLocal = new javax.swing.JLabel();
        jButtonCadastrarCliente = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelJustificativa.setText("Justificativa:");

        jTextFieldJustificativa.setText(projeto.getJustificativa());

        jLabelDemocratizacao.setText("Democratizacao:");

        jLabelAcessibilidade.setText("Acessibilidade:");

        jLabelPublicoEstimado.setText("Publico Estimado:");

        jLabelOrcamento.setText("Orcamento:");

        jLabelStatus.setText("Status:");

        jTextFieldDemocratizacao.setText(projeto.getDemocratizacao());

        jTextFieldAcessibilidade.setText(projeto.getAcessibilidade());

        jTextFieldPublicoEstimado.setText(String.valueOf(projeto.getPublicoEstimado()));

        jTextFieldOrcamento.setText(String.valueOf(projeto.getOrcamento()));
        jTextFieldOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOrcamentoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Editar Projeto");

        jButton2.setText("Voltar");

        jLabelNome.setText("Nome:");

        jLabelCliente.setText("Cliente:");

        jTextFieldNome.setText(projeto.getNome());

        jLabelDescricao.setText("Descricao:");

        jLabelArtista.setText("Artista:");

        jTextFieldDescricao.setText(projeto.getDescricao());
        jTextFieldDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescricaoActionPerformed(evt);
            }
        });

        jButtonCadastrarArtistas.setText("Cadastrar");
        jButtonCadastrarArtistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarArtistasActionPerformed(evt);
            }
        });

        jLabelObjetivo.setText("Objetivo:");

        jLabelProdutos.setText("Produtos:");

        jTextFieldObjetivo.setText(projeto.getObjetivo());

        jButtonCadastrarProdutos.setText("Cadastrar");

        jButtonSalvar.setText("Atualizar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jTextFieldLocal.setText(projeto.getLocal());

        jLabelLocal.setText("Local:");

        jButtonCadastrarCliente.setText("Cadastrar");
        jButtonCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarClienteActionPerformed(evt);
            }
        });

        DefaultComboBoxModel dlm = new DefaultComboBoxModel();
        Status[] s = Status.values();
        for(int i=0; i<Status.values().length ;i++)
        	dlm.addElement(s[i]);
        
        jComboBox1.setModel(dlm);
        jComboBox1.setSelectedItem(projeto.getStatus().name());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(130, 130, 130)
                .addComponent(jButton2)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jButtonSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelLocal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelDescricao, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelObjetivo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelJustificativa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelDemocratizacao, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAcessibilidade, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPublicoEstimado, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelOrcamento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelStatus, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelArtista, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelProdutos, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jTextFieldDescricao)
                            .addComponent(jTextFieldObjetivo)
                            .addComponent(jTextFieldLocal)
                            .addComponent(jTextFieldJustificativa)
                            .addComponent(jTextFieldDemocratizacao)
                            .addComponent(jTextFieldAcessibilidade)
                            .addComponent(jTextFieldPublicoEstimado)
                            .addComponent(jTextFieldOrcamento)
                            .addComponent(jButtonCadastrarArtistas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCadastrarProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCadastrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCliente)
                    .addComponent(jButtonCadastrarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLocal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelObjetivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldJustificativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJustificativa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDemocratizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDemocratizacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAcessibilidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAcessibilidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPublicoEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPublicoEstimado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOrcamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelArtista)
                    .addComponent(jButtonCadastrarArtistas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProdutos)
                    .addComponent(jButtonCadastrarProdutos))
                .addGap(34, 34, 34)
                .addComponent(jButtonSalvar)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOrcamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOrcamentoActionPerformed

    private void jTextFieldDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescricaoActionPerformed

    private void jButtonCadastrarArtistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarArtistasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadastrarArtistasActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        //        try {
            //            Cliente_CRUD.incluirCliente(this.txnome.getText(),this.txtelefone.getText(),this.txemail.getText());
            //            Login login = new Login();
            //            login.setVisible(true);
            //            dispose();
            //        } catch (Exception ex) {
            //            Logger.getLogger(Incluir_Cliente.class.getName()).log(Level.SEVERE, null, ex);
            //        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarClienteActionPerformed
		try {
	        Cliente[] clientes = Cliente_CRUD.listarClientes(Main.arqClientes);
	        if(clientes!=null){
	            ListarClientes lc = new ListarClientes();
	            lc.setVisible(true);
	        }else{
	            JOptionPane.showConfirmDialog(null, "Nao existem clientes cadastrados");
	        }
		} catch (Exception e) {
			e.printStackTrace();
		}
    }//GEN-LAST:event_jButtonCadastrarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editar_Projetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editar_Projetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editar_Projetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editar_Projetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editar_Projetos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCadastrarArtistas;
    private javax.swing.JButton jButtonCadastrarCliente;
    private javax.swing.JButton jButtonCadastrarProdutos;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAcessibilidade;
    private javax.swing.JLabel jLabelArtista;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelDemocratizacao;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelJustificativa;
    private javax.swing.JLabel jLabelLocal;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelObjetivo;
    private javax.swing.JLabel jLabelOrcamento;
    private javax.swing.JLabel jLabelProdutos;
    private javax.swing.JLabel jLabelPublicoEstimado;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JTextField jTextFieldAcessibilidade;
    private javax.swing.JTextField jTextFieldDemocratizacao;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldJustificativa;
    private javax.swing.JTextField jTextFieldLocal;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldObjetivo;
    private javax.swing.JTextField jTextFieldOrcamento;
    private javax.swing.JTextField jTextFieldPublicoEstimado;
    // End of variables declaration//GEN-END:variables
}
